package nl.hackyourfuture.dojoserver.volunteer.dto;

import io.swagger.v3.oas.annotations.media.Schema;
import nl.hackyourfuture.dojoserver.shared.model.Gender;
import nl.hackyourfuture.dojoserver.volunteer.Volunteer;
import nl.hackyourfuture.dojoserver.volunteer.VolunteerStatus;

@Schema(description = "A volunteer profile as returned by the API")
public record VolunteerResponse(
        @Schema(
                description = "Unique identifier of the volunteer, generated by the server",
                example = "VOLUNTEERID",
                requiredMode = Schema.RequiredMode.REQUIRED
        )
        String id,

        @Schema(
                description = "The URL to the volunteer profile picture",
                example = "/api/volunteers/VOLUNTEERID/picture/PICTUREID",
                requiredMode = Schema.RequiredMode.REQUIRED,
                nullable = true
        )
        String pictureUrl,

        @Schema(
                description = "The URL to a smaller version of the volunteer profile picture",
                example = "/api/volunteers/VOLUNTEERID/picture/PICTUREID/thumbnail",
                requiredMode = Schema.RequiredMode.REQUIRED,
                nullable = true
        )
        String thumbnailUrl,

        @Schema(
                description = "The volunteer's full name for display",
                example = "Jane Roe",
                requiredMode = Schema.RequiredMode.REQUIRED
        )
        String displayName,

        @Schema(
                description = "Helper for the client to build a unique path to use in client routing.",
                example = "/volunteer/jane-roe_Vq7mKp2XaB",
                requiredMode = Schema.RequiredMode.REQUIRED
        )
        String profilePath,

        @Schema(
                description = "The first name of the volunteer",
                example = "Jane",
                requiredMode = Schema.RequiredMode.REQUIRED
        )
        String firstName,

        @Schema(
                description = "The last name of the volunteer",
                example = "Roe",
                requiredMode = Schema.RequiredMode.REQUIRED
        )
        String lastName,

        @Schema(
                description = "How the volunteer describes their gender",
                example = "woman",
                requiredMode = Schema.RequiredMode.REQUIRED,
                nullable = true
        )
        Gender gender,

        @Schema(
                description = "The pronouns the volunteer goes by",
                example = "She/her",
                requiredMode = Schema.RequiredMode.REQUIRED,
                nullable = true
        )
        String pronouns,

        @Schema(
                description = "The company the volunteer works for",
                example = "Acme B.V.",
                requiredMode = Schema.RequiredMode.REQUIRED,
                nullable = true
        )
        String companyName,

        @Schema(
                description = "The volunteer's job role at their company",
                example = "Senior Developer",
                requiredMode = Schema.RequiredMode.REQUIRED,
                nullable = true
        )
        String jobRole,

        @Schema(
                description = "The volunteer's email address. Unique across all volunteers.",
                example = "jane.roe@example.com",
                requiredMode = Schema.RequiredMode.REQUIRED
        )
        String email,

        @Schema(
                description = "A phone number the volunteer can be reached on",
                example = "+31612345678",
                requiredMode = Schema.RequiredMode.REQUIRED,
                nullable = true
        )
        String phone,

        @Schema(
                description = "The volunteer's GitHub username, without the URL",
                example = "janeroe",
                requiredMode = Schema.RequiredMode.REQUIRED,
                nullable = true
        )
        String githubHandle,

        @Schema(
                description = "The volunteer's Slack member id",
                example = "U068AQ9G99F",
                requiredMode = Schema.RequiredMode.REQUIRED,
                nullable = true
        )
        String slackId,

        @Schema(
                description = "The URL to the volunteer's LinkedIn profile",
                example = "https://linkedin.com/in/jane-roe",
                requiredMode = Schema.RequiredMode.REQUIRED,
                nullable = true
        )
        String linkedinUrl,

        @Schema(
                description = "Whether the volunteer is currently helping out",
                example = "active",
                requiredMode = Schema.RequiredMode.REQUIRED
        )
        VolunteerStatus status,

        @Schema(
                description = "Free-form notes about the volunteer",
                example = "Mentors on Tuesday evenings.",
                requiredMode = Schema.RequiredMode.REQUIRED,
                nullable = true
        )
        String notes
) {
    public static VolunteerResponse from(Volunteer volunteer) {
        return new VolunteerResponse(
                volunteer.getId(),
                volunteer.getPictureUrl(),
                volunteer.getThumbnailUrl(),
                volunteer.getDisplayName(),
                volunteer.getProfilePath(),
                volunteer.getFirstName(),
                volunteer.getLastName(),
                volunteer.getGender(),
                volunteer.getPronouns(),
                volunteer.getCompanyName(),
                volunteer.getJobRole(),
                volunteer.getEmail(),
                volunteer.getPhone(),
                volunteer.getGithubHandle(),
                volunteer.getSlackId(),
                volunteer.getLinkedinUrl(),
                volunteer.getStatus(),
                volunteer.getNotes());
    }
}
