package nl.hackyourfuture.dojoserver.trainee.employmenthistory.dto;

import io.swagger.v3.oas.annotations.media.Schema;
import nl.hackyourfuture.dojoserver.trainee.employmenthistory.EmploymentHistory;
import nl.hackyourfuture.dojoserver.trainee.employmenthistory.EmploymentType;

import java.math.BigDecimal;
import java.time.LocalDate;

@Schema(description = "An employment record of a trainee as returned by the API")
public record EmploymentHistoryResponse(
        @Schema(
                description = "Unique identifier of the employment record, generated by the server",
                example = "g5HQGuL8Zq",
                requiredMode = Schema.RequiredMode.REQUIRED
        )
        String id,

        @Schema(
                description = "The type of the position",
                example = "job",
                requiredMode = Schema.RequiredMode.REQUIRED
        )
        EmploymentType type,

        @Schema(
                description = "The name of the employer",
                example = "HackYourFuture",
                requiredMode = Schema.RequiredMode.REQUIRED
        )
        String companyName,

        @Schema(
                description = "The job title the trainee holds",
                example = "Frontend developer",
                requiredMode = Schema.RequiredMode.REQUIRED
        )
        String role,

        @Schema(
                description = "The date the trainee started the position",
                example = "2024-01-15",
                requiredMode = Schema.RequiredMode.REQUIRED
        )
        LocalDate startDate,

        @Schema(
                description = "The date the position ended. Empty while the trainee is still there.",
                example = "2025-01-15",
                requiredMode = Schema.RequiredMode.REQUIRED,
                nullable = true
        )
        LocalDate endDate,

        @Schema(
                description = "Whether HackYourFuture collected a placement fee for this position",
                example = "true",
                requiredMode = Schema.RequiredMode.REQUIRED
        )
        Boolean feeCollected,

        @Schema(
                description = "The placement fee in euros",
                example = "500.00",
                requiredMode = Schema.RequiredMode.REQUIRED,
                nullable = true
        )
        BigDecimal feeAmount,

        @Schema(
                description = "Free-form notes about this position",
                example = "Contract extended for another year.",
                requiredMode = Schema.RequiredMode.REQUIRED,
                nullable = true
        )
        String comments
) {
    public static EmploymentHistoryResponse from(EmploymentHistory employmentHistory) {
        return new EmploymentHistoryResponse(
                employmentHistory.getId(),
                employmentHistory.getType(),
                employmentHistory.getCompanyName(),
                employmentHistory.getRole(),
                employmentHistory.getStartDate(),
                employmentHistory.getEndDate(),
                employmentHistory.getFeeCollected(),
                employmentHistory.getFeeAmount(),
                employmentHistory.getComments());
    }
}
