package nl.hackyourfuture.dojoserver.interaction.dto;

import io.swagger.v3.oas.annotations.media.Schema;
import nl.hackyourfuture.dojoserver.admin.user.dto.ReporterResponse;
import nl.hackyourfuture.dojoserver.interaction.Interaction;
import nl.hackyourfuture.dojoserver.interaction.InteractionType;

import java.time.Instant;

@Schema(description = "An interaction with a trainee as returned by the API")
public record InteractionResponse(
        @Schema(
                description = "Unique identifier of the interaction, generated by the server",
                example = "g5HQGuL8Zq",
                requiredMode = Schema.RequiredMode.REQUIRED
        )
        String id,

        @Schema(
                description = "The moment the interaction took place",
                example = "2024-01-15T14:30:00Z",
                requiredMode = Schema.RequiredMode.REQUIRED
        )
        Instant date,

        @Schema(
                description = "The kind of interaction",
                example = "feedback",
                requiredMode = Schema.RequiredMode.REQUIRED
        )
        InteractionType type,

        @Schema(
                description = "A short summary of the interaction",
                example = "Discussed final project scope",
                requiredMode = Schema.RequiredMode.REQUIRED
        )
        String title,

        @Schema(
                description = "What was discussed during the interaction",
                requiredMode = Schema.RequiredMode.REQUIRED
        )
        String details,

        @Schema(
                description = "The user who recorded this interaction.",
                requiredMode = Schema.RequiredMode.REQUIRED,
                nullable = true // TODO: remove after authentication is implemented
        )
        ReporterResponse reporter
) {
    public static InteractionResponse from(Interaction interaction) {
        return new InteractionResponse(
                interaction.getId(),
                interaction.getDate(),
                interaction.getType(),
                interaction.getTitle(),
                interaction.getDetails(),
                interaction.getReporter() == null ? null : ReporterResponse.from(interaction.getReporter()));
    }
}
