package nl.hackyourfuture.dojoserver.authentication.dto;

import io.swagger.v3.oas.annotations.media.Schema;
import nl.hackyourfuture.dojoserver.authentication.AuthenticatedUser;

@Schema(description = "The signed-in user")
public record SessionResponse(
        @Schema(
                description = "Unique identifier of the user, generated by the server",
                example = "WTh1qLhy3K",
                requiredMode = Schema.RequiredMode.REQUIRED
        )
        String userId,

        @Schema(
                description = "The display name of the user",
                example = "John Doe",
                requiredMode = Schema.RequiredMode.REQUIRED
        )
        String name,

        @Schema(
                description = "The user Email. Used for authentication.",
                example = "user@example.com",
                requiredMode = Schema.RequiredMode.REQUIRED
        )
        String email,

        @Schema(
                description = "The URL to the user image",
                example = "/api/admin/users/USERID/picture/PICTUREID",
                requiredMode = Schema.RequiredMode.REQUIRED,
                nullable = true
        )
        String pictureUrl
) {
    public static SessionResponse from(AuthenticatedUser user) {
        return new SessionResponse(user.id(), user.name(), user.email(), user.pictureUrl());
    }
}
