spring:
  application:
    name: dojo-server-dev

# API Docs
scalar:
  enabled: true

# Health and metrics
management:
  endpoint:
    health:
      show-details: always

# Authentication
dojo:
  auth:
    cookie-secure: false
