package nl.hackyourfuture.dojoserver.partner.organisation.dto;

import io.swagger.v3.oas.annotations.media.Schema;
import nl.hackyourfuture.dojoserver.admin.user.User;
import nl.hackyourfuture.dojoserver.admin.user.dto.ReporterResponse;
import nl.hackyourfuture.dojoserver.partner.organisation.Organisation;
import nl.hackyourfuture.dojoserver.partner.organisation.OrganisationStatus;
import nl.hackyourfuture.dojoserver.partner.organisation.PartnershipType;

import java.util.List;
import java.util.Map;
import java.util.Objects;

@Schema(description = "A partner organisation as returned by the API")
public record OrganisationResponse(
        @Schema(
                description = "Unique identifier of the organisation, generated by the server",
                example = "Xk2pQ9rTbW",
                requiredMode = Schema.RequiredMode.REQUIRED
        )
        String id,

        @Schema(
                description = "The URL to the organisation's logo",
                example = "/api/organisations/ORGANISATIONID/picture/PICTUREID",
                requiredMode = Schema.RequiredMode.REQUIRED,
                nullable = true
        )
        String pictureUrl,

        @Schema(
                description = "The URL to a smaller version of the organisation's logo",
                example = "/api/organisations/ORGANISATIONID/picture/PICTUREID/thumbnail",
                requiredMode = Schema.RequiredMode.REQUIRED,
                nullable = true
        )
        String thumbnailUrl,

        @Schema(
                description = "The name of the organisation",
                example = "Acme B.V.",
                requiredMode = Schema.RequiredMode.REQUIRED
        )
        String name,

        @Schema(
                description = "Helper for the client to build a unique path to use in client routing.",
                example = "/organisation/acme-b-v_Xk2pQ9rTbW",
                requiredMode = Schema.RequiredMode.REQUIRED
        )
        String profilePath,

        @Schema(
                description = "The URL to the organisation's website",
                example = "https://example.com",
                requiredMode = Schema.RequiredMode.REQUIRED,
                nullable = true
        )
        String websiteUrl,

        @Schema(
                description = "The URL to the organisation's LinkedIn page",
                example = "https://linkedin.com/company/acme",
                requiredMode = Schema.RequiredMode.REQUIRED,
                nullable = true
        )
        String linkedinUrl,

        @Schema(
                description = "The city the organisation is based in",
                example = "Amsterdam",
                requiredMode = Schema.RequiredMode.REQUIRED,
                nullable = true
        )
        String location,

        @Schema(
                description = "Where the partnership with the organisation stands",
                example = "active",
                requiredMode = Schema.RequiredMode.REQUIRED
        )
        OrganisationStatus status,

        @Schema(
                description = "What the organisation can offer HYF",
                example = "[\"funding\", \"events\"]",
                requiredMode = Schema.RequiredMode.REQUIRED
        )
        List<PartnershipType> partnershipTypes,

        @Schema(
                description = "The users responsible for the organisation, the primary first",
                requiredMode = Schema.RequiredMode.REQUIRED
        )
        List<ReporterResponse> responsibles,

        @Schema(
                description = "Free-form notes about the organisation",
                example = "Hires two Back-End interns every cohort.",
                requiredMode = Schema.RequiredMode.REQUIRED,
                nullable = true
        )
        String notes
) {
    // An id whose user is gone is left out rather than failing the response.
    public static OrganisationResponse from(Organisation organisation, Map<String, User> users) {
        return new OrganisationResponse(
                organisation.getId(),
                organisation.getPictureUrl(),
                organisation.getThumbnailUrl(),
                organisation.getName(),
                organisation.getProfilePath(),
                organisation.getWebsiteUrl(),
                organisation.getLinkedinUrl(),
                organisation.getLocation(),
                organisation.getStatus(),
                organisation.getPartnershipTypes().stream().sorted().toList(),
                organisation.getResponsibleIds().stream()
                        .map(users::get)
                        .filter(Objects::nonNull)
                        .map(ReporterResponse::from)
                        .toList(),
                organisation.getNotes());
    }
}
