package nl.hackyourfuture.dojoserver.partner.organisation.dto;

import io.swagger.v3.oas.annotations.media.Schema;
import nl.hackyourfuture.dojoserver.partner.organisation.Organisation;
import nl.hackyourfuture.dojoserver.partner.organisation.OrganisationStatus;

@Schema(description = "Organisation summary.")
public record OrganisationSummaryResponse(
        @Schema(
                description = "Unique identifier of the organisation, generated by the server",
                example = "Xk2pQ9rTbW",
                requiredMode = Schema.RequiredMode.REQUIRED
        )
        String id,

        @Schema(
                description = "The name of the organisation",
                example = "Acme B.V.",
                requiredMode = Schema.RequiredMode.REQUIRED
        )
        String name,

        @Schema(
                description = "Helper for the client to build a unique path to use in client routing.",
                example = "/organisation/acme-b-v_Xk2pQ9rTbW",
                requiredMode = Schema.RequiredMode.REQUIRED
        )
        String profilePath,

        @Schema(
                description = "The URL to a smaller version of the organisation's logo",
                example = "/api/organisations/ORGANISATIONID/picture/PICTUREID/thumbnail",
                requiredMode = Schema.RequiredMode.REQUIRED,
                nullable = true
        )
        String thumbnailUrl,

        @Schema(
                description = "The URL to the organisation's website",
                example = "https://example.com",
                requiredMode = Schema.RequiredMode.REQUIRED,
                nullable = true
        )
        String websiteUrl,

        @Schema(
                description = "The URL to the organisation's LinkedIn page",
                example = "https://linkedin.com/company/acme",
                requiredMode = Schema.RequiredMode.REQUIRED,
                nullable = true
        )
        String linkedinUrl,

        @Schema(
                description = "The city the organisation is based in",
                example = "Amsterdam",
                requiredMode = Schema.RequiredMode.REQUIRED,
                nullable = true
        )
        String location,

        @Schema(
                description = "Where the partnership with the organisation stands",
                example = "active",
                requiredMode = Schema.RequiredMode.REQUIRED
        )
        OrganisationStatus status
) {
    public static OrganisationSummaryResponse from(Organisation organisation) {
        return new OrganisationSummaryResponse(
                organisation.getId(),
                organisation.getName(),
                organisation.getProfilePath(),
                organisation.getThumbnailUrl(),
                organisation.getWebsiteUrl(),
                organisation.getLinkedinUrl(),
                organisation.getLocation(),
                organisation.getStatus());
    }
}
