package nl.hackyourfuture.dojoserver.partner.contactperson.dto;

import io.swagger.v3.oas.annotations.media.Schema;
import nl.hackyourfuture.dojoserver.partner.contactperson.ContactPerson;

@Schema(description = "A contact person at a partner organisation as returned by the API")
public record ContactPersonResponse(
        @Schema(
                description = "Unique identifier of the contact person, generated by the server",
                example = "q7LmZ2cVnR",
                requiredMode = Schema.RequiredMode.REQUIRED
        )
        String id,

        @Schema(
                description = "The full name of the contact person",
                example = "Jane Roe",
                requiredMode = Schema.RequiredMode.REQUIRED
        )
        String name,

        @Schema(
                description = "The email address of the contact person",
                example = "jane.roe@example.com",
                requiredMode = Schema.RequiredMode.REQUIRED,
                nullable = true
        )
        String email,

        @Schema(
                description = "A phone number the contact person can be reached on",
                example = "+31612345678",
                requiredMode = Schema.RequiredMode.REQUIRED,
                nullable = true
        )
        String phone,

        @Schema(
                description = "The URL to the contact person's LinkedIn profile",
                example = "https://linkedin.com/in/jane-roe",
                requiredMode = Schema.RequiredMode.REQUIRED,
                nullable = true
        )
        String linkedinUrl,

        @Schema(
                description = "The role of the contact person at the organisation",
                example = "Talent Acquisition Lead",
                requiredMode = Schema.RequiredMode.REQUIRED,
                nullable = true
        )
        String jobTitle,

        @Schema(
                description = "Free-form notes about the contact person",
                example = "Prefers a call over email.",
                requiredMode = Schema.RequiredMode.REQUIRED,
                nullable = true
        )
        String notes
) {
    public static ContactPersonResponse from(ContactPerson contactPerson) {
        return new ContactPersonResponse(
                contactPerson.getId(),
                contactPerson.getName(),
                contactPerson.getEmail(),
                contactPerson.getPhone(),
                contactPerson.getLinkedinUrl(),
                contactPerson.getJobTitle(),
                contactPerson.getNotes());
    }
}
