package nl.hackyourfuture.dojoserver.trainee.assessment.dto;

import io.swagger.v3.oas.annotations.media.Schema;
import nl.hackyourfuture.dojoserver.trainee.assessment.Assessment;
import nl.hackyourfuture.dojoserver.trainee.assessment.AssessmentResult;
import nl.hackyourfuture.dojoserver.trainee.assessment.AssessmentType;

import java.math.BigDecimal;
import java.time.LocalDate;

@Schema(description = "An assessment of a trainee as returned by the API")
public record AssessmentResponse(
        @Schema(
                description = "Unique identifier of the assessment, generated by the server",
                example = "g5HQGuL8Zq",
                requiredMode = Schema.RequiredMode.REQUIRED
        )
        String id,

        @Schema(
                description = "The date the assessment took place",
                example = "2024-01-15",
                requiredMode = Schema.RequiredMode.REQUIRED
        )
        LocalDate date,

        @Schema(
                description = "The assessment the trainee took",
                example = "core-end-interview",
                requiredMode = Schema.RequiredMode.REQUIRED
        )
        AssessmentType type,

        @Schema(
                description = "The outcome of the assessment",
                example = "passed",
                requiredMode = Schema.RequiredMode.REQUIRED
        )
        AssessmentResult result,

        @Schema(
                description = "The score of the assessment. Empty for an assessment that is not graded.",
                example = "8.6",
                requiredMode = Schema.RequiredMode.REQUIRED,
                nullable = true
        )
        BigDecimal score,

        @Schema(
                description = "Free-form notes about this assessment",
                requiredMode = Schema.RequiredMode.REQUIRED,
                nullable = true
        )
        String comments
) {
    public static AssessmentResponse from(Assessment assessment) {
        return new AssessmentResponse(
                assessment.getId(),
                assessment.getDate(),
                assessment.getType(),
                assessment.getResult(),
                assessment.getScore(),
                assessment.getComments());
    }
}
