export const strikeComments = [
  'Submitted React exam 20 minutes late—claimed their cat sat on the keyboard at the worst possible moment.',
  'Sent final project link 5 hours late—apparently, the WiFi only decided to betray them right before submission.',
  'Backend assignment submitted 12 hours late—thought today was yesterday and yesterday was today.',
  'Missed weekly check-in, no communication—possibly abducted by aliens, but no evidence was provided.',
  'Q&A question submitted 24 hours late—forgot which timezone they were in (despite never leaving their apartment).',
  "Forgot to submit final assignment, sent it 3 days later—said their laptop 'needed a break.'",
  "No attendance at check-in call, no explanation—sent a message later saying, 'Oh wait, was that today?'",
  'Missed check-in, informed 45 minutes after it ended—claimed their clock had been running slow for months.',
  'Missed check-in, realized 1 hour later and apologized—excuse involved an elaborate coffee spill incident.',
  "No updates regarding assignment deadline—said they were 'manifesting a deadline extension.'",
  'No communication about absence in class—when asked, simply responded with a gif of a raccoon hiding under a blanket.',
  'Q&A question posted after 25 hours—claimed they were lost in a rabbit hole of Stack Overflow discussions.',
  'Did not submit Q&A question—when confronted, sent a meme instead of an explanation.',
  "Submitted project feedback a day late—said they were 'giving it time to mature like fine wine.'",
  "Arrived 15 minutes late for group discussion—blamed an 'existential crisis at an inconvenient time.'",
  'Missed peer review session, later apologized—said their cat sat on their notes (again!).',
  "Missed peer review session, no communication—claimed 'technical difficulties' but admitted later they just overslept.",
  "Submitted Node.js exam 18 minutes late—blamed 'cosmic forces beyond their control.'",
  "30 minutes late, no explanation given—when asked, just said 'Monday.'",
  "No assignment submission, no communication—claimed to be 'testing the limits of academic forgiveness.'",
  "No assignment submitted, provided excuse after being asked—said they had 'misplaced their motivation.'",
  "Late for check-in call, did not inform—blamed a 'tragic breakfast situation.'",
  "'11:30: Hey, I won't be able to make it today. Something came up. Sorry.' No prior notice.",
  "Missed cohort meeting without notifying anyone—claimed they were 'trapped in a very philosophical conversation with themselves.'",
  'No communication regarding repeated absences. Scheduled discussion—when asked, responded with a deep sigh.',
  'Missed check-in for the third time, required a follow-up call—suggested that maybe the universe was conspiring against them.',
  "Missed meeting due to assignment corrections, 20 minutes late—claimed they were 'lost in the code matrix.'",
  'Missed scheduled one-on-one meeting—claimed their alarm clock betrayed them.',
  "Missed scheduled one-on-one meeting—blamed a pigeon that wouldn't let them leave their balcony.",
  '15 minutes late to check-in, minimal explanation—said they got stuck debating whether to attend or not.',
  '30 minutes late for offline Q&A, apologized afterward—blamed an urgent snack run.',
  "Did not attend check-in call, no explanation—later admitted they were 'power napping' and overdid it.",
  "Submitted JavaScript test 7 minutes late—claimed they had to 'double-check if JavaScript still worked.'",
  "No preparation exercise submitted—said they were 'conducting an experiment on procrastination.'",
  "No preparation exercise submitted—blamed 'Monday energy.'",
  "Submitted video project without audio, no prior communication—said they wanted to 'leave room for interpretation.'",
  "No feedback on video project, replied a day later—claimed they were 'waiting for inspiration to strike.'",
  "14 minutes late for scheduled technical interview—blamed an 'unexpected philosophical conversation with a barista.'",
  "Did not submit required Q&A question—said they 'didn't want to waste anyone's time with mediocre questions.'",
  "Assignment submitted a day late, no explanation—blamed 'a deep, inexplicable sense of time dilation.'",
  "Assignment submitted two days late, no explanation—claimed their computer 'needed a break.'",
  "Assignment submitted late for the third time, issued official warning—said they were 'testing the limits of forgiveness.'",
  "Forgot about UsingAPIs W3 assignment deadline—said their API calls were 'emotionally unavailable.'",
  'Missed offline session due to confusion, asked to attend online—claimed their map app led them to the wrong city.',
  "Missed check-in call, no prior notice—later messaged saying 'time is a social construct.'",
  "Notified 10 minutes before workshop that they would be late—blamed 'an intense debate with their reflection.'",
  "20 minutes late for Q&A session—claimed their cat stole their chair and they couldn't sit down.",
  '25 minutes late, cited personal reasons—later admitted it was a nap gone wrong.',
  "Deadline moved forward, submitted work a day late—said they needed to 'grieve the lost time.'",
  "Deadline moved forward, submitted work in the evening after the session—claimed they 'needed the extra pressure.'",
  "Late without prior communication, warned about strike policy—said they were 'caught in a staring contest with their computer screen.'",
  "Missed check-in call, no message—later blamed an 'unusually aggressive daydream.'",
  'Missed check-in call, no message—claimed their phone was on a spiritual journey.',
  "Missed check-in call, no message—said they were 'lost in deep thought.'",
  "15 minutes late, no prior update—blamed an 'unexpected existential crisis.'",
  "Thought class was elsewhere, attended online instead—said their internal GPS was 'on the fritz.'",
  'Informed 5 minutes after start that they’d join soon—joined 15 minutes later.',
  '10 minutes late, no reason given—when asked, responded with a mysterious smiley face.',
  "6 minutes late for check-in, no response to messages—claimed their clock 'betrayed them.'",
  "Missed class due to bus delay, notified afterward—said they 'put too much faith in public transport.'",
  'No preparation work submitted, mentioned later that they were sick—only after being asked.',
  "8 minutes late for interview, no communication—blamed 'a rabbit hole of coding memes.'",
  "Submitted assignment one day late without communication—claimed their code 'needed one last pep talk.'",
  'Missed scheduled project review—said their WiFi took a break.',
  "No presence at study group session, no explanation—later said 'the vibes were off.'",
  "12 minutes late for call, provided a vague excuse—'life happened.'",
  "Arrived late for meeting, apologized an hour later—blamed 'sudden, unexplained exhaustion.'",
  "Did not show up to one-on-one mentoring call—said they were 'following their heart, which unfortunately led them elsewhere.'",
];
