package nl.hackyourfuture.dojoserver.trainee.profile.dto;

import io.swagger.v3.oas.annotations.media.Schema;
import nl.hackyourfuture.dojoserver.trainee.profile.Gender;
import nl.hackyourfuture.dojoserver.trainee.profile.Trainee;

@Schema(description = "A trainee profile as returned by the API")
public record TraineeResponse(
        @Schema(
                description = "Unique identifier of the trainee, generated by the server",
                example = "HpOjvmwXsL",
                requiredMode = Schema.RequiredMode.REQUIRED
        )
        String id,

        @Schema(
                description = "The URL to the trainee profile picture",
                example = "https://example.org/profile.jpg",
                requiredMode = Schema.RequiredMode.REQUIRED,
                nullable = true
        )
        String imageUrl,

        @Schema(
                description = "The URL to a smaller version of the trainee profile picture",
                example = "https://example.org/profile_thumb.jpg",
                requiredMode = Schema.RequiredMode.REQUIRED,
                nullable = true
        )
        String thumbnailUrl,

        @Schema(
                description = "The legal first name of the trainee",
                example = "John",
                requiredMode = Schema.RequiredMode.REQUIRED
        )
        String firstName,

        @Schema(
                description = "The legal last name of the trainee",
                example = "Doe",
                requiredMode = Schema.RequiredMode.REQUIRED
        )
        String lastName,

        @Schema(
                description = "The name the trainee prefers to be called",
                example = "Johnny",
                requiredMode = Schema.RequiredMode.REQUIRED,
                nullable = true
        )
        String preferredName,

        @Schema(
                description = "The trainee Email. Unique across all trainees.",
                example = "john.doe@example.com",
                requiredMode = Schema.RequiredMode.REQUIRED
        )
        String email,

        @Schema(
                description = "How the trainee describes their gender",
                example = "non-binary",
                requiredMode = Schema.RequiredMode.REQUIRED,
                nullable = true
        )
        Gender gender,

        @Schema(
                description = "The pronouns the trainee goes by",
                example = "They/them",
                requiredMode = Schema.RequiredMode.REQUIRED,
                nullable = true
        )
        String pronouns
) {
    public static TraineeResponse from(Trainee trainee) {
        return new TraineeResponse(
                trainee.getId(),
                trainee.getImageUrl(),
                trainee.getThumbnailUrl(),
                trainee.getFirstName(),
                trainee.getLastName(),
                trainee.getPreferredName(),
                trainee.getEmail(),
                trainee.getGender(),
                trainee.getPronouns());
    }
}
