package nl.hackyourfuture.dojoserver.trainee.profile.dto;

import io.swagger.v3.oas.annotations.media.Schema;
import nl.hackyourfuture.dojoserver.trainee.profile.Trainee;

@Schema(description = "A trainee as listed in a collection. The full profile is at /api/trainees/{id}.")
public record TraineeSummaryResponse(
        @Schema(
                description = "Unique identifier of the trainee, generated by the server",
                example = "HpOjvmwXsL",
                requiredMode = Schema.RequiredMode.REQUIRED
        )
        String id,

        @Schema(
                description = "The legal first name of the trainee",
                example = "John",
                requiredMode = Schema.RequiredMode.REQUIRED
        )
        String firstName,

        @Schema(
                description = "The legal last name of the trainee",
                example = "Doe",
                requiredMode = Schema.RequiredMode.REQUIRED
        )
        String lastName,

        @Schema(
                description = "The name the trainee prefers to be called",
                example = "Johnny",
                requiredMode = Schema.RequiredMode.REQUIRED,
                nullable = true
        )
        String preferredName,

        @Schema(
                description = "The URL to the trainee profile picture",
                example = "https://example.org/profile.jpg",
                requiredMode = Schema.RequiredMode.REQUIRED,
                nullable = true
        )
        String imageUrl,

        @Schema(
                description = "The URL to a smaller version of the trainee profile picture",
                example = "https://example.org/profile_thumb.jpg",
                requiredMode = Schema.RequiredMode.REQUIRED,
                nullable = true
        )
        String thumbnailUrl
) {
    public static TraineeSummaryResponse from(Trainee trainee) {
        return new TraineeSummaryResponse(
                trainee.getId(),
                trainee.getFirstName(),
                trainee.getLastName(),
                trainee.getPreferredName(),
                trainee.getImageUrl(),
                trainee.getThumbnailUrl());
    }
}
