package nl.hackyourfuture.dojoserver.trainee.profile.dto;

import io.swagger.v3.oas.annotations.media.Schema;
import nl.hackyourfuture.dojoserver.trainee.profile.JobPath;
import nl.hackyourfuture.dojoserver.trainee.profile.LearningStatus;
import nl.hackyourfuture.dojoserver.trainee.profile.Track;
import nl.hackyourfuture.dojoserver.trainee.profile.Trainee;

import java.math.BigDecimal;

@Schema(description = "Trainee summary.")
public record TraineeSummaryResponse(
        @Schema(
                description = "Unique identifier of the trainee, generated by the server",
                example = "TRAINEEID",
                requiredMode = Schema.RequiredMode.REQUIRED
        )
        String id,

        @Schema(
                description = "The trainee name for display. If a preferred name is set, it will use it over the first name",
                example = "John Doe",
                requiredMode = Schema.RequiredMode.REQUIRED
        )
        String displayName,

        @Schema(
                description = "Helper for the client to build a unique path to use in client routing.",
                example = "/trainee/john-doe_c9JoIbbD",
                requiredMode = Schema.RequiredMode.REQUIRED
        )
        String profilePath,

        @Schema(
                description = "The URL to a smaller version of the trainee profile picture",
                example = "/api/trainees/TRAINEEID/picture/PICTUREID/thumbnail",
                requiredMode = Schema.RequiredMode.REQUIRED,
                nullable = true
        )
        String thumbnailUrl,

        @Schema(
                description = "Where the trainee stands in the program",
                example = "studying",
                requiredMode = Schema.RequiredMode.REQUIRED
        )
        LearningStatus learningStatus,

        @Schema(
                description = "Where the trainee stands in finding work",
                example = "searching",
                requiredMode = Schema.RequiredMode.REQUIRED
        )
        JobPath jobPath,

        @Schema(
                description = "The track the trainee is studying",
                example = "core-program",
                requiredMode = Schema.RequiredMode.REQUIRED
        )
        Track track,

        @Schema(
                description = "The city the trainee lives in",
                example = "Amsterdam",
                requiredMode = Schema.RequiredMode.REQUIRED,
                nullable = true
        )
        String location,

        @Schema(
                description = "The mean of the trainee's best score per assessment type. Null until an assessment is scored.",
                example = "8.25",
                requiredMode = Schema.RequiredMode.REQUIRED,
                nullable = true
        )
        BigDecimal averageAssessmentScore,

        @Schema(
                description = "The trainee Email. Unique across all trainees.",
                example = "john.doe@example.com",
                requiredMode = Schema.RequiredMode.REQUIRED
        )
        String email,

        @Schema(
                description = "The trainee's Slack member id",
                example = "U068AQ9G99F",
                requiredMode = Schema.RequiredMode.REQUIRED,
                nullable = true
        )
        String slackId,

        @Schema(
                description = "The trainee's GitHub username, without the URL",
                example = "johndoe",
                requiredMode = Schema.RequiredMode.REQUIRED,
                nullable = true
        )
        String githubHandle,

        @Schema(
                description = "The URL to the trainee's LinkedIn profile",
                example = "https://linkedin.com/in/john-doe",
                requiredMode = Schema.RequiredMode.REQUIRED,
                nullable = true
        )
        String linkedinUrl,

        @Schema(
                description = "The cohort the trainee currently studies with",
                example = "53",
                requiredMode = Schema.RequiredMode.REQUIRED,
                nullable = true
        )
        Integer cohort
) {
    public static TraineeSummaryResponse from(Trainee trainee, BigDecimal averageAssessmentScore) {
        return new TraineeSummaryResponse(
                trainee.getId(),
                trainee.getDisplayName(),
                trainee.getProfilePath(),
                trainee.getThumbnailUrl(),
                trainee.getLearningStatus(),
                trainee.getJobPath(),
                trainee.getTrack(),
                trainee.getLocation(),
                averageAssessmentScore,
                trainee.getEmail(),
                trainee.getSlackId(),
                trainee.getGithubHandle(),
                trainee.getLinkedinUrl(),
                trainee.getCurrentCohort());
    }
}
