package nl.hackyourfuture.dojoserver.admin.user.dto;

import io.swagger.v3.oas.annotations.media.Schema;
import nl.hackyourfuture.dojoserver.admin.user.User;

@Schema(description = "The user who reported a record, as embedded in that record")
public record ReporterResponse(
        @Schema(
                description = "Unique identifier of the user, generated by the server",
                example = "WTh1qLhy3K",
                requiredMode = Schema.RequiredMode.REQUIRED
        )
        String id,

        @Schema(
                description = "The display name of the user",
                example = "John Doe",
                requiredMode = Schema.RequiredMode.REQUIRED
        )
        String name,

        @Schema(
                description = "The URL to the user image",
                example = "https://example.org/profile.jpg",
                requiredMode = Schema.RequiredMode.REQUIRED,
                nullable = true
        )
        String imageUrl
) {
    public static ReporterResponse from(User user) {
        return new ReporterResponse(user.getId(), user.getName(), user.getImageUrl());
    }
}
