package nl.hackyourfuture.dojoserver.admin.user.dto;

import io.swagger.v3.oas.annotations.media.Schema;
import nl.hackyourfuture.dojoserver.admin.user.User;

@Schema(description = "A user account as returned by the API")
public record UserResponse(
        @Schema(
                description = "Unique identifier of the user, generated by the server",
                example = "WTh1qLhy3K",
                requiredMode = Schema.RequiredMode.REQUIRED
        )
        String id,
        @Schema(
                description = "Email address of the user",
                example = "user@example.com",
                requiredMode = Schema.RequiredMode.REQUIRED
        )
        String email
) {
    public static UserResponse from(User user) {
        return new UserResponse(
                user.getId(),
                user.getEmail()
        );
    }
}
