package nl.hackyourfuture.dojoserver.admin.user.dto;

import io.swagger.v3.oas.annotations.media.Schema;
import nl.hackyourfuture.dojoserver.admin.user.User;

@Schema(description = "A user account as returned by the API")
public record UserResponse(
        @Schema(
                description = "Unique identifier of the user, generated by the server",
                example = "WTh1qLhy3K",
                requiredMode = Schema.RequiredMode.REQUIRED
        )
        String id,

        @Schema(
                description = "The user Email. Used for authentication.",
                example = "user@example.com",
                requiredMode = Schema.RequiredMode.REQUIRED
        )
        String email,

        @Schema(
                description = "The display name of the user",
                example = "John Doe",
                requiredMode = Schema.RequiredMode.REQUIRED
        )
        String name,

        @Schema(
                description = "The URL to the user picture",
                example = "/api/admin/users/USERID/picture/PICTUREID",
                requiredMode = Schema.RequiredMode.REQUIRED,
                nullable = true
        )
        String pictureUrl,

        @Schema(
                description = "The URL to a smaller version of the user picture",
                example = "/api/admin/users/USERID/picture/PICTUREID/thumbnail",
                requiredMode = Schema.RequiredMode.REQUIRED,
                nullable = true
        )
        String thumbnailUrl,

        @Schema(
                description = "User active status. Non active users cannot log in.",
                example = "true",
                requiredMode = Schema.RequiredMode.REQUIRED
        )
        boolean isActive
) {
    public static UserResponse from(User user) {
        return new UserResponse(
                user.getId(),
                user.getEmail(),
                user.getName(),
                user.getPictureUrl(),
                user.getThumbnailUrl(),
                user.isActive());
    }
}
